# Generated by Django 6.0.1 on 2026-01-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestaboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestamessage',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vestaboard.vestaboard'),
            preserve_default=False,
        ),
    ]
