# Generated by Django 6.0.1 on 2026-01-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestaboard', '0002_vestamessage_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestamessage',
            name='transition',
            field=models.CharField(choices=[('column', 'Column'), ('reverse-column', 'Reverse Column'), ('edges-to-center', 'Edges to Center'), ('row', 'Row'), ('diagonal', 'Diagonal'), ('random', 'Random')], default=None),
            preserve_default=False,
        ),
    ]
