# Generated by Django 6.0.1 on 2026-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestaboard', '0003_vestamessage_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestamessage',
            name='horizontal_alignment',
            field=models.CharField(choices=[('top', 'Left'), ('middle', 'Center'), ('bottom', 'Right'), ('justified', 'Justified')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='vestamessage',
            name='vertical_alignment',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('justified', 'Justified')], default=None, null=True),
        ),
    ]
