#!/bin/bash
# Script to setup TLS via certbot

sudo apt update
sudo apt-get remove certbot
sudo apt install python3 python3-dev python3-venv libaugeas-dev gcc

sudo python3 -m venv /opt/certbot/
sudo /opt/certbot/bin/pip install --upgrade pip
sudo /opt/certbot/bin/pip install certbot certbot-nginx
sudo ln -s /opt/certbot/bin/certbot /usr/local/bin/certbot
sudo /opt/certbot/bin/pip install certbot-dns-cloudflare

sudo certbot certonly \
  --dns-cloudflare \
  --dns-cloudflare-credentials /root/.certbot-secrets \
  -d vestaweb.app